version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      root-deps:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /api
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      api-deps:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /ui
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      ui-deps:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: docker
    directory: /api
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: docker
    directory: /nginx
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
